
Vagrant.configure(2) do |config|
  config.vm.box = "williamyeh/centos7-docker"
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true
  config.vm.synced_folder "VmFiles/", "/home/vagrant/data"


  config.vm.define :marathon1 do |server|
    server.vm.hostname = 'marathon1'
    server.vm.network :private_network, :ip => '192.168.11.101'
    server.vm.provision :hostmanager
    server.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
    end
  end

  config.vm.define :marathon2 do |server|
    server.vm.hostname = 'marathon2'
    server.vm.network :private_network, :ip => '192.168.11.102'
    server.vm.provision :hostmanager
    server.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
    end
  end

  config.vm.define :marathon3 do |server|
    server.vm.hostname = 'marathon3'
    server.vm.network :private_network, :ip => '192.168.11.103'
    server.vm.provision :hostmanager
    server.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
    end
  end

end
