
Vagrant.configure(2) do |config|
  config.vm.box = "williamyeh/centos7-docker"
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true
  config.vm.synced_folder "synced/", "/home/synced/"

  config.vm.define :FRDev do |server|
    server.vm.hostname = 'FRDev'
    server.vm.network :private_network, :ip => '192.168.11.100'
    server.vm.provision :hostmanager
    server.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
    end
  end

end
