
Vagrant.configure(2) do |config|
  config.vm.box = "williamyeh/centos7-docker"
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true
  config.vm.synced_folder "synced/", "/home/synced/"

  config.vm.define :Adaptive do |server|
    server.vm.hostname = 'Adaptive'
    server.vm.network :private_network, :ip => '192.168.100.1'
    server.vm.provision :hostmanager
    server.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 2
    end
  end

end
