
Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.hostmanager.enabled = true
  config.vm.provision :shell, path: "bootstrap.sh"

  config.vm.define :Centos7 do |server|
    server.vm.hostname = 'Centos7'
    server.vm.network :private_network, :ip => '192.168.1.1'
    server.vm.provision :hostmanager
    server.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 2
    end
  end

end
