
Vagrant.configure(2) do |config|
  config.vm.box = "williamyeh/centos7-docker"
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true

 config.vm.define :sparkgateway do |server|
    server.vm.hostname = 'sparkgateway'
    server.vm.network :private_network, :ip => '192.168.33.200'
    server.vm.provision :hostmanager
    server.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
    end
  end

  config.vm.define :kafka1 do |server|
    server.vm.hostname = 'kafka1'
    server.vm.network :private_network, :ip => '192.168.33.204'
    server.vm.provision :hostmanager
    server.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
    end
  end

  config.vm.define :kafka2 do |server|
    server.vm.hostname = 'kafka2'
    server.vm.network :private_network, :ip => '192.168.33.205'
    server.vm.provision :hostmanager
    server.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
    end
  end

  config.vm.define :kafka3 do |server|
    server.vm.hostname = 'kafka3'
    server.vm.network :private_network, :ip => '192.168.33.206'
    server.vm.provision :hostmanager
    server.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
    end
  end
end
